version: 0.2

phases:
  install:
    runtime-versions:
        java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
        - echo Build started on `date`
        - cat s3-bucket-template.yml
        - cat parameters.json
        - aws cloudformation create-stack --stack-name devops-training-stack-task-2 --template-body file://./s3-bucket-template.yml --parameters file://./parameters.json
  post_build:
    commands:
      - echo Build completed on `date`