AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Stack that will create ACM Certificate

Parameters:
  DomainNameValue:
    Description: 'Domain Name'
    Type: String

Resources:
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainNameValue
      DomainValidationOptions:
      - DomainName: !Ref DomainNameValue
        ValidationDomain: !Ref DomainNameValue
      ValidationMethod: 'DNS'        

Outputs:
  CertificateArn:
    Value: !Ref ACMCertificate
    Description: 'ARN for ACM Certificate'
    Export:
      Name: dt-acm-cert-arn