AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "SampleTopic"

  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: salman.saeed@northbaysolutions.net
      Protocol: email
      TopicArn: !Ref 'MySNSTopic'