--- 
version: 0.2 
phases: 
  install: 
    commands: 
      - npm -v 
    runtime-versions: 
      nodejs: 10 
  pre_build: 
    commands: 
      - echo "Pre-build" 
  build: 
    commands: 
      - echo "Starting build" 
  post_build: 
    commands: 
      - echo "Post-build" 
      - cd $CODEBUILD_SRC_DIR 
      - aws s3 rm "s3://${staticWebBucketName}/" --recursive 
artifacts: 
  type: zip 
  files: 
    - '**/*' 